#!/usr/bin/env bash

# Run external tests (mostly smoke tests)

# Author: Walker Hale (hale@bcm.edu), 2012
#         Human Genome Sequencing Center, Baylor College of Medicine
#
# This file is part of Pipe-o-matic.
#
# Pipe-o-matic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pipe-o-matic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.

set -e  # Exit upon error.

export TEST_ROOT=$(cd $(dirname "$0"); pwd)
source "$TEST_ROOT"/lib/test-setup.sh

cd "$TEST_ROOT"  # not strictly necessary

for case_dir in $(ls -r "$TEST_ROOT"/cases); do
    if [[ -z "$QUIET" ]]; then
        echo $case_dir
    fi
    test_case_path="$TEST_ROOT"/cases/"$case_dir"
    output_path="$PROJECT_ROOT"/target/test/"$case_dir"
    rm -rf "$output_path"
    mkdir -p "$output_path"
    mkdir "$output_path"/execute
    mkdir "$output_path"/expect
    ln -s .pmatic "$output_path"/execute/pmatic
    PYTHONPATH="$TEST_PYTHONPATH" "$test_case_path"/test "$output_path"
    ERR=$?
    if [[ $ERR != 0 ]]; then
        echo $case_dir failed
        exit $ERR
    fi
done

echo SUCCESS
