#!/usr/bin/env bash

export TEST_ROOT=$(cd $(dirname "$0"); pwd)
export PROJECT_ROOT=$(dirname "$TEST_ROOT")
export REFINERY_BASE="$TEST_ROOT"/refinery_base

cd "$TEST_ROOT"

for case_dir in $(ls "$TEST_ROOT"/cases); do
    echo $case_dir
    test_case_path="$TEST_ROOT"/cases/"$case_dir"
    output_path="$PROJECT_ROOT"/target/test/"$case_dir"
    rm -rf "$output_path"
    mkdir -p "$output_path"
    mkdir "$output_path"/execute
    mkdir "$output_path"/expect
    "$test_case_path"/test "$output_path"
done
