#!/usr/bin/env bash

# Check for code style

# Author: Walker Hale (hale@bcm.edu), 2012
#         Human Genome Sequencing Center, Baylor College of Medicine
#
# This file is part of Pipe-o-matic.
#
# Pipe-o-matic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pipe-o-matic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.

export TEST_ROOT=$(cd $(dirname "$0"); pwd)
source "$TEST_ROOT"/lib/test-setup.sh

cd "$PROJECT_ROOT"

if [[ $(type -P pep8) ]]; then
    pep8 bin/pmatic* lib/*.py test/lib/*.py
fi
