#!/usr/bin/env bash

# Single case test script

# Author: Walker Hale (hale@bcm.edu), 2012
#         Human Genome Sequencing Center, Baylor College of Medicine
#
# This file is part of Pipe-o-matic.
#
# Pipe-o-matic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pipe-o-matic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.

output_path="$1"

# Generate expected results.
cp data/foo-input "$output_path"/expect/
(  # Use a sub-shell to isolate side-effects.
    set -e  # Exit upon error.
    cd "$output_path"/expect/
    "$TEST_ROOT"/dummies/bar-1.1/bin/bar >bar.log
    cat foo-input | "$TEST_ROOT"/dummies/foo-1.0/bin/foo 123 abc >foo.log
)

# Generate pipeline results.
cp data/foo-input "$output_path"/execute/
(  # Use a sub-shell to isolate side-effects.
    set -e  # Exit upon error.
    if [[ "$VERBOSE" ]]; then
        PMATIC_OPTS='-v'
    fi
    "$PROJECT_ROOT"/bin/pmatic $PMATIC_OPTS bar-1 "$output_path"/execute run
    "$PROJECT_ROOT"/bin/pmatic $PMATIC_OPTS foo-1 "$output_path"/execute run
)
if [[ $? != 0 ]]; then
    echo "Error in $0"
fi

# Compare.
diff -qr "$output_path"/expect "$output_path"/execute
