#!/usr/bin/env bash

# Verify that pmaticrun will prevent execution of a pipeline when the base
# directory is in an error state.

# Author: Walker Hale (hale@bcm.edu), 2012
#         Human Genome Sequencing Center, Baylor College of Medicine
#
# This file is part of Pipe-o-matic.
#
# Pipe-o-matic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pipe-o-matic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.

setup "$@"

# Generate expected results.
(  # Use a sub-shell to isolate side-effects.
# Deliberate fail script
cat >"$expect_path"/probe <<EOD
#!/usr/bin/env bash
exit 42
EOD

chmod +x "$expect_path"/probe

touch "$expect_path"/probe.err

cat >"$expect_path"/probe.out <<EOD
probe on
probe off
EOD
)
check_expected

# Generate pipeline results.
cp "$expect_path"/probe "$execute_path"/
should_fail 1 "$pmaticrun" $PMATIC_OPTS run-probe-1 "$execute_path"
should_fail 2 "$pmaticrun" $PMATIC_OPTS bar-1 "$execute_path"

compare
