#!/usr/bin/env bash

# Testing pmaticstatus during pipeline execution
# Verify that pmaticstatus prints "started" during pipeline execution.

# Author: Walker Hale (hale@bcm.edu), 2012
#         Human Genome Sequencing Center, Baylor College of Medicine
#
# This file is part of Pipe-o-matic.
#
# Pipe-o-matic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Pipe-o-matic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pipe-o-matic.  If not, see <http://www.gnu.org/licenses/>.

setup "$@"

# Generate expected results.
(  # Use a sub-shell to isolate side-effects.
cat >"$expect_path"/probe <<EOD
#!/usr/bin/env bash
"$pmaticstatus" .
EOD

chmod +x "$expect_path"/probe

touch "$expect_path"/probe.err

cat >"$expect_path"/probe.out <<EOD
probe on
started
probe off
EOD
)
check_expected

# Generate pipeline results.
(  # Use a sub-shell to isolate side-effects.
    cp "$expect_path"/probe "$execute_path"/
    "$pmaticrun" $PMATIC_OPTS run-probe-1 "$execute_path"
)
check_execute

compare
